INSERT INTO users (username, email, password, role)
VALUES ('annie_ananas', 'annieananas@bakehub.com', 'wachtwoord123', 'USER'),
       ('bobbybanaan', 'bobbiebanaan@bakehub.com', 'wachtwoord123', 'USER'),
       ('wendywatermeloen', 'wendywatermeloen@bakehub.com', 'wachtwoord123', 'ADMIN'),
       ('lolalimoen95', 'lolalimoen@bakehub.com', 'wachtwoord123', 'USER'),
       ('fredframb00s', 'fredframboos@bakehub.com', 'wachtwoord123', 'ADMIN'),
       ('brambrownie', 'brambrownie@bakehub.com', 'wachtwoord123', 'ADMIN');

INSERT INTO categories (name, description, image_url)
VALUES ('taart',
        'Of je nu aan de slag wilt met een klassieke appeltaart, een frisse citroenkwarktaart of gewoon een simpele chocoladetaart, hier vind je volop inspiratie. Perfect voor verjaardagen, een high tea of gewoon omdat je er zin in hebt!',
        NULL),
       ('cake',
        'Van een luchtige vanillecake tot een smeuïge kruidcake: hier ontdek je een hele verzameling cakes die altijd in de smaak vallen. Handig voor verjaardagen, onverwacht bezoek of gewoon een gezellige middag thuis.',
        NULL),
       ('koekjes',
        'Een koek bij de koffie vindt iedereen lekker. Je vind hier de lekkerste koekjesrecepten, van knapperige speculaasjes en klassieke stroopwafels tot simpele zandkoekjes.',
        NULL),
       ('brood',
        'Zin in knapperig volkorenbrood, ambachtelijke bolletjes of zoete kaneelbroodjes? Je vindt hier vast het juiste recept. Niets gaat boven de geur van zelfgebakken brood in huis!',
        NULL),
       ('hartig',
        'Baksels hoeven niet altijd zoet te zijn. Denk aan hartige taarten, saucijzenbroodjes en quiches - ideaal voor de lunch, een borrel of als hartig tussendoortje!',
        NULL);

INSERT INTO recipes (name, image_url, description, instructions, servings, preparation_time, rating, category_id)
VALUES ('Speculoos cheesecake',
        NULL,
        'Een romige no-bake cheesecake met een kruidige speculoosbodem en speculoospasta.',
        '1. Verkruimel speculooskoekjes en meng met gesmolten boter. 2. Druk de kruimels stevig in een vorm en laat opstijven. 3. Klop roomkaas, slagroom en speculoospasta luchtig. 4. Giet het mengsel op de bodem en strijk glad. 5. Laat de cheesecake minimaal 4 uur opstijven in de koelkast.',
        10,
        30,
        4.5,
        1),
       ('Speculaascake',
        NULL,
        'Een zachte kruidige cake, perfect voor herfst en winter.',
        '1. Klop boter en suiker romig. 2. Voeg eieren toe en mix tot een glad beslag. 3. Zeef bloem en speculaaskruiden erdoor. 4. Giet het beslag in een cakeblik. 5. Bak 55 minuten op 160°C tot de cake goudbruin is.',
        18,
        80,
        5,
        2),
       ('Gevuld Speculaas',
        NULL,
        'Een klassiek Sinterklaasgebak met zachte amandelspijs',
        '1. Maak een deeg van bloem, boter, suiker en speculaaskruiden. 2. Laat het deeg een uur rusten in de koelkast. 3. Meng amandelspijs met ei voor de vulling. 4. Rol het deeg uit, verdeel de spijs ertussen en leg er een tweede deeglaag op. 5. Bak 35 minuten op 175°C.',
        16,
        90,
        4,
        3),
       ('Suikerbrood',
        NULL,
        'Een zoet, zacht brood met parelsuiker en een vleugje kaneel.',
        '1. Meng bloem, gist, melk en boter tot een soepel deeg. 2. Laat het deeg 1 uur rijzen. 3. Kneed parelsuiker en kaneel voorzichtig door het deeg. 4. Vorm een brood en leg in een ingevette vorm. 5. Laat nog 30 minuten rijzen en bak 35 minuten op 180°C.',
        15,
        120,
        4,
        4),
       ('Kerstboom Plaattaart',
        NULL,
        'Een feestelijke bladerdeeghap in kerstboomvorm, gevuld met roomkaas, pesto en gegrilde groenten.',
        '1. Snijd bladerdeeg in een kerstboomvorm. 2. Meng roomkaas met groene pesto. 3. Bestrijk de plak met het mengsel. 4. Verdeel gegrilde paprika en courgette erover. 5. Dek af met een tweede laag bladerdeeg en bak 20 minuten op 200°C tot goudbruin.',
        8,
        40,
        4.5,
        5);


